### ISSUE TITLE
Implement web vitals tracking

### ISSUE THREAD

**Issue by ammar-ahmed22** [ammar-ahmed22/ammarahmed.ca#80]
Using reportWebVitals with React, implement tracking of this data.

## Tasks
- [ ] Create a database on MongoDB Atlas (same DB to use for chess game), analytics will be saved to analytics collection
- [ ] Create queries and mutations for sending and receiving web vital data
    * [ ] addAnayltics -> Mutation
    * [ ] analytics -> Query
    * [ ] averageAnalytics -> Query
- [ ] Purge data from DB that is older than 1 month (maybe 2 weeks)
    * [ ] Create index on "createdAt", with "expireAfterSeconds" 
- [ ] Create a dashboard on the website which displays the monthly average for the relevant values and explains them
